export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const OTP_SENT = 'OTP_SENT';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const HOME_PRODUCTS_FETCH_START = 'FEATURED_PRODUCTS_FETCH_START';
export const HOME_PRODUCTS_FETCH_SUCCESS = 'FEATURED_PRODUCTS_FETCH_SUCCESS';
export const HOME_PRODUCTS_FETCH_FAILD = 'FEATURED_PRODUCTS_FETCH_FAILD';

export const FETCH_PRODUCTS_DETAILS_START = 'FETCH_PRODUCTS_DETAILS_START';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAILD = 'FETCH_PRODUCTS_DETAILS_FAILD';

export const FETCH_PRODUCTS_BRANDS_START = 'FETCH_PRODUCTS_BRANDS_START';
export const FETCH_PRODUCTS_BRANDS_SUCCESS = 'FETCH_PRODUCTS_BRANDS_SUCCESS';
export const FETCH_PRODUCTS_BRANDS_FAILD = 'FETCH_PRODUCTS_BRANDS_FAILD';

export const FETCH_ALL_CATEGORY_START = 'FETCH_ALL_CATEGORY_START';
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS';
export const FETCH_ALL_CATEGORY_FAILD = 'FETCH_ALL_CATEGORY_FAILD';

export const FETCH_SUPPLIER_START = 'FETCH_SUPPLIER_START';
export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';
export const FETCH_SUPPLIER_FAILD = 'FETCH_SUPPLIER_FAILD';

export const FETCH_SUPPLIER_DETAILS_START = 'FETCH_SUPPLIER_DETAILS_START';
export const FETCH_SUPPLIER_DETAILS_SUCCESS = 'FETCH_SUPPLIER_DETAILS_SUCCESS';
export const FETCH_SUPPLIER_DETAILS_FAILD = 'FETCH_SUPPLIER_DETAILS_FAILD';

export const FETCH_SUPPLIER_PRODUCTS_START = 'FETCH_SUPPLIER_PRODUCTS_START';
export const FETCH_SUPPLIER_PRODUCTS_SUCCESS =
  'FETCH_SUPPLIER_PRODUCTS_SUCCESS';
export const FETCH_SUPPLIER_PRODUCTS_FAILD = 'FETCH_SUPPLIER_PRODUCTS_FAILD';

export const FETCH_USER_CART = 'FETCH_USER_CART';
export const FETCH_USER_CART_ERROR = 'FETCH_USER_CART_ERROR';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';

export const FETCH_PRICING_DETAILS_STATRT = 'FETCH_PRICING_DETAILS_STATRT';
export const FETCH_PRICING_DETAILS_SUCCESS = 'FETCH_PRICING_DETAILS_SUCCESS';
export const FETCH_PRICING_DETAILS_ERROR = 'FETCH_PRICING_DETAILS_ERROR';

export const DELETE_FROM_CART_START = 'DELETE_FROM_CART_START';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_FROM_CART_ERROR = 'DELETE_FROM_CART_ERROR';

export const APPLY_COUPON_START = 'APPLY_COUPON_START';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_ERROR = 'APPLY_COUPON_ERROR';
