export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const OTP_SENT = 'OTP_SENT';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const HOME_PRODUCTS_FETCH_START = 'FEATURED_PRODUCTS_FETCH_START';
export const HOME_PRODUCTS_FETCH_SUCCESS = 'FEATURED_PRODUCTS_FETCH_SUCCESS';
export const HOME_PRODUCTS_FETCH_FAILD = 'FEATURED_PRODUCTS_FETCH_FAILD';

export const FETCH_PRODUCTS_DETAILS_START = 'FETCH_PRODUCTS_DETAILS_START';
export const FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS';
export const FETCH_PRODUCTS_DETAILS_FAILD = 'FETCH_PRODUCTS_DETAILS_FAILD';
