export enum CartActionTypes {
  FETCH_CART_START = 'FETCH_CART_START',
  FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILD = 'FETCH_CART_FAILD',

  INCREASE_QUANTITY_START = 'INCREASE_QUANTITY_START',
  INCREASE_QUANTITY_SUCCESS = 'INCREASE_QUANTITY_SUCCESS',
  INCREASE_QUANTITY_FAILD = 'INCREASE_QUANTITY_FAILD',

  DECREASE_QUANTITY_START = 'DECREASE_QUANTITY_START',
  DECREASE_QUANTITY_SUCCESS = 'DECREASE_QUANTITY_SUCCESS',
  DECREASE_QUANTITY_FAILD = 'DECREASE_QUANTITY_FAILD',

  COUPON_ADD_START = 'COUPON_ADD_START',
  COUPON_ADD_SUCCESS = 'COUPON_ADD_SUCCESS',
  COUPON_ADD_FAILD = 'COUPON_ADD_FAILD',
}
