export enum CategoryTypes {
  FETCH_ALL_CATEGORY_START = 'FETCH_ALL_CATEGORY_START',
  FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS',
  FETCH_ALL_CATEGORY_FAILD = 'FETCH_ALL_CATEGORY_FAILD',
}
