export enum ActionType {
  //Home Products
  HOME_PRODUCTS_FETCH_START = 'HOME_PRODUCTS_FETCH_START',
  HOME_PRODUCTS_FETCH_SUCCESS = 'HOME_PRODUCTS_FETCH_SUCCESS',
  HOME_PRODUCTS_FETCH_FAILD = 'HOME_PRODUCTS_FETCH_FAILD',
  //Product details
  FETCH_PRODUCTS_DETAILS_START = 'FETCH_PRODUCTS_DETAILS_START',
  FETCH_PRODUCTS_DETAILS_SUCCESS = 'FETCH_PRODUCTS_DETAILS_SUCCESS',
  FETCH_PRODUCTS_DETAILS_FAILD = 'FETCH_PRODUCTS_DETAILS_FAILD',
  //Product by brand
  FETCH_PRODUCTS_BRANDS_START = 'FETCH_PRODUCTS_BRANDS_START',
  FETCH_PRODUCTS_BRANDS_SUCCESS = 'FETCH_PRODUCTS_BRANDS_SUCCESS',
  FETCH_PRODUCTS_BRANDS_FAILD = 'FETCH_PRODUCTS_BRANDS_FAILD',
}
