export enum ProductDetailsActionType {
  FETCH_PRODUCT_DETAILS_START = 'FETCH_PRODUCT_DETAILS_START',
  FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_FAILD = 'FETCH_PRODUCT_DETAILS_FAILD',

  CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_START = 'CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_START',
  CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_SUCCESS = 'CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_SUCCESS',
  CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_FAILD = 'CHECK_CAN_ADD_TO_CART_SPECIFIC_PRODUCT_FAILD',
}
