export enum SupplierActiontypes {
  FETCH_SUPPLIER_START = 'FETCH_SUPPLIER_START',
  FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS',
  FETCH_SUPPLIER_FAILD = 'FETCH_SUPPLIER_FAILD',
  FETCH_SUPPLIER_DETAILS_START = 'FETCH_SUPPLIER_DETAILS_START',
  FETCH_SUPPLIER_DETAILS_SUCCESS = 'FETCH_SUPPLIER_DETAILS_SUCCESS',
  FETCH_SUPPLIER_DETAILS_FAILD = 'FETCH_SUPPLIER_DETAILS_FAILD',
  FETCH_SUPPLIER_PRODUCTS_START = 'FETCH_SUPPLIER_PRODUCTS_START',
  FETCH_SUPPLIER_PRODUCTS_SUCCESS = 'FETCH_SUPPLIER_PRODUCTS_SUCCESS',
  FETCH_SUPPLIER_PRODUCTS_FAILD = 'FETCH_SUPPLIER_PRODUCTS_FAILD',
  FETCH_PRODUCTS_BRANDS_START = 'FETCH_PRODUCTS_BRANDS_START',
  FETCH_PRODUCTS_BRANDS_SUCCESS = 'FETCH_PRODUCTS_BRANDS_SUCCESS',
  FETCH_PRODUCTS_BRANDS_FAILD = 'FETCH_PRODUCTS_BRANDS_FAILD',
}
